version: '3'

volumes:
  production_django_media: {}
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  #production_elasticsearch_data: {}

services:
  prod_django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: cotr_production_django
    volumes:
      - production_django_media:/app/cotr/media:rw
    depends_on:
      - prod_postgres
      - prod_redis
      #- elasticsearch
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  prod_nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: cotr_production_nginx
    depends_on:
      - prod_django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro

  prod_postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: cotr_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  prod_traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: cotr_production_traefik
    depends_on:
      - prod_django
      - prod_nginx
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '8201:80'
#      - '0.0.0.0:443:443'

  prod_redis:
    image: redis:5.0
  #elasticsearch:
  #image: elasticsearch:7.5.1
  #volumes:
  #- production_elasticsearch_data:/usr/share/elasticsearch/data
  #env_file:
  #- ./.envs/.production/.elasticsearch
  #ports:
  #- '127.0.0.1:9200:9200'
  #- '127.0.0.1:9300:9300'
  #kibana:
  #image: kibana:7.5.1
  #depends_on:
  #- elasticsearch
  #env_file:
  #- ./.envs/.production/.kibana
  #ports:
  #- '5601:5601'
