version: '3'

volumes:
  staging_django_media: {}
  staging_postgres_data: {}
  staging_postgres_data_backups: {}
  staging_traefik: {}
  #staging_elasticsearch_data: {}

services:
  stg_django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: cotr_staging_django
    volumes:
      - staging_django_media:/app/cotr/media:rw
    depends_on:
      - stg_postgres
      - stg_redis
      #- elasticsearch
    env_file:
      - ./.envs/.staging/.django
      - ./.envs/.staging/.postgres
    command: /start

  stg_nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: cotr_staging_nginx
    depends_on:
      - stg_django
    volumes:
      - staging_django_media:/usr/share/nginx/media:ro

  stg_postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: cotr_staging_postgres
    volumes:
      - staging_postgres_data:/var/lib/postgresql/data
      - staging_postgres_data_backups:/backups
    env_file:
      - ./.envs/.staging/.postgres

  stg_traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: cotr_staging_traefik
    depends_on:
      - stg_django
      - stg_nginx
    volumes:
      - staging_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:8202:80'
#      - '0.0.0.0:443:443'

  stg_redis:
    image: redis:5.0
  #elasticsearch:
  #image: elasticsearch:7.5.1
  #volumes:
  #- production_elasticsearch_data:/usr/share/elasticsearch/data
  #env_file:
  #- ./.envs/.production/.elasticsearch
  #ports:
  #- '127.0.0.1:9200:9200'
  #- '127.0.0.1:9300:9300'
  #kibana:
  #image: kibana:7.5.1
  #depends_on:
  #- elasticsearch
  #env_file:
  #- ./.envs/.production/.kibana
  #ports:
  #- '5601:5601'
